apiVersion: skaffold/v2beta8
kind: Config
build:
  artifacts:
    - image: eshop-backend-simple
      context: eshop-backend
      jib: {}
    - image: eshop-frontend-simple
      context: eshop-frontend
deploy:
  kubectl:
    manifests:
      - k8s/**.yaml
profiles:
- name: gke
  build:
    googleCloudBuild:
      projectId: architect-certification-289902
  deploy:
    kubeContext: gke_architect-certification-289902_asia-northeast3-c_skaffold-demo-cluster