apiVersion: skaffold/v2beta8
kind: Config
build:
  artifacts:
    - image: eshop-backend-simple
      context: eshop-backend
      jib: {}
    - image: eshop-frontend-simple
      context: eshop-frontend
deploy:
  kubectl:
    manifests:
      - k8s/**.yaml