apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:13
        env:
          - name: POSTGRES_USER
            value: eshop_user
          - name: POSTGRES_DB
            value: eshop_db
          - name: POSTGRES_PASSWORD
            value: password
        ports:
        - containerPort: 5432